//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WATCH.rc
//
#define IDD_PAINT1                      30
#define IDD_PAINT2                      31
#define IDD_PAINT3                      32
#define IDB_BITMAP0                     112
#define IDB_BITMAP1                     113
#define IDB_BITMAP2                     114
#define IDB_BITMAP3                     115
#define IDB_BITMAP4                     116
#define IDB_BITMAP5                     117
#define IDB_BITMAP6                     118
#define IDB_BITMAP7                     119
#define IDB_BITMAP8                     120
#define IDB_BITMAP9                     121
#define IDB_BITMAP_SEMICOLON            122
#define IDB_ABOUT                       125
#define IDB_SM_BITMAP0                  126
#define IDB_SM_BITMAP1                  127
#define IDB_SM_BITMAP2                  128
#define IDB_SM_BITMAP3                  129
#define IDB_SM_BITMAP4                  130
#define IDB_SM_BITMAP5                  131
#define IDB_SM_BITMAP6                  132
#define IDB_SM_BITMAP7                  133
#define IDB_SM_BITMAP8                  134
#define IDB_SM_BITMAP9                  135
#define IDB_SM_SEMICOLON                136
#define IDM_TOPMOST                     40001
#define IDM_24                          40002
#define IDM_EXIT                        40003
#define IDM_ABOUT                       40004
#define IDM_STOPCD                      40006
#define IDM_PLAYCD                      40007
#define IDC_PAINT1                      -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
