//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDB_BACKGROUND                  101
#define IDB_BUTTON0                     102
#define IDB_BUTTON1                     103
#define IDB_BUTTON2                     104
#define IDB_BUTTON3                     105
#define IDB_BUTTON4                     106
#define IDB_BUTTON5                     107
#define IDB_BUTTON6                     108
#define IDB_BUTTON7                     109
#define IDB_BUTTON8                     110
#define IDB_BUTTON9                     111
#define IDB_BUTTONB                     112
#define IDB_BUTTONR                     113
#define IDB_BUTTONRUN                   113
#define IDB_BUTTON_RESTART              114
#define IDB_EXIT                        115
#define IDB_BUTTONS0                    116
#define IDB_BUTTONS1                    117
#define IDB_BUTTONS2                    118
#define IDB_BUTTONS3                    119
#define IDB_BUTTONS4                    120
#define IDB_BUTTONS5                    121
#define IDB_BUTTONS6                    122
#define IDB_BUTTONS7                    123
#define IDB_BUTTONS8                    124
#define IDB_BUTTONS9                    125
#define IDB_BUTTONSB                    126
#define IDB_BUTTONSR                    126
#define IDB_BUTTONSRUN                  127
#define IDB_BUTTON_RESTARTS             128
#define IDB_EXITS                       129
#define IDB_DATE0                       130
#define IDB_DATE1                       131
#define IDB_DATE2                       132
#define IDB_DATE3                       133
#define IDB_DATE4                       134
#define IDB_DATE5                       135
#define IDB_DATE6                       136
#define IDB_DATE7                       137
#define IDB_DATE8                       138
#define IDB_DATE9                       139
#define IDB_DATE_NULL                   239
#define IDB_BALL_RED                    240
#define IDB_BALL_BLUE                   241
#define IDB_BALL_GREEN                  242

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
