//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by iq120.rc
//
#define IDM_MENU                        1
#define IDM_EXIT                        2
#define IDM_ABOUT                       3
#define IDI_ICON1                       101
#define IDC_CURSOR1                     102
#define IDB_BITMAP1                     103
#define IDB_BITMAP2                     104
#define IDD_DIALOG1                     105
#define IQ120                           106
#define IDD_IQ120                       108
#define IDB_BITMAP3                     113
#define IDC_RADIO1                      1000
#define IDC_RADIO2                      1001
#define IDC_SCROLLBAR1                  1002
#define IDC_SPIN1                       1003
#define IDC_CUSTOM1                     1004
#define IDC_CHECK1                      1005
#define IDC_EDIT1                       1006
#define IDC_ANIMATE1                    1007
#define IDC_BUTTON1                     1008
#define IDB_ABOUT                       1008
#define IDB_END                         1009
#define IDB_RESTART                     1010
#define ID_BACK                         40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
